#!/usr/bin/env python3
"""Deterministic, dependency-free DSP baseline probes for CheapSynth01.

VCF CSVs in this directory are archival Phase 2 probes of the removed biquad
model and are not regenerated by this script. Remaining probes are explicitly
idealized signal-path references, not executions of the production plugin.
"""
import csv, math, os, platform

OUT = os.path.join(os.path.dirname(__file__), '..', 'artifacts', 'dsp')

def write(name, header, rows):
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, name), 'w', newline='') as f:
        w=csv.writer(f); w.writerow(header); w.writerows(rows)

def run():
    # VCA one-pole HP cumulative response of documented 40 Hz, 20 Hz and preserved coupling poles.
    vca=[]
    for hz in (8.18,10.3,16.35,20,30,40,60,100):
      fs=44100; w=2*math.pi*hz/fs
      hp=lambda alpha: abs((1-complex(math.cos(-w),math.sin(-w)))/(1-alpha*complex(math.cos(-w),math.sin(-w))))
      stages=[hp(math.exp(-2*math.pi*40/fs)),hp(math.exp(-2*math.pi*20/fs)),hp(.997),hp(.9995)]
      for mask in range(16):
       gain=math.prod(g for i,g in enumerate(stages) if mask&(1<<i))
       phase=math.degrees(sum(math.atan2(math.sin(w), math.exp(-2*math.pi*hz/fs)-math.cos(w)) for i in range(4) if mask&(1<<i)))
       vca.append((44100,hz,mask,20*math.log10(max(gain,1e-15)),phase))
    write('vca_low_frequency.csv',['sample_rate','frequency_hz','enabled_stage_mask_input_hp_dc_tr7_output','gain_db','phase_degrees'],vca)
    # Analytic harmonic reference for ideal periodic waveforms; excludes actual oscillator bandlimiting.
    voc=[]
    for note in (24,36,48,60,72):
      f=440*2**((note-69)/12)
      for wave in ('triangle','sawtooth','square','pulse','pwm'):
       duty=.25 if wave in ('pulse','pwm') else .5
       for h in range(1,min(64,int(22050/f))+1):
        if wave=='triangle': amp=8/(math.pi**2*h*h) if h%2 else 0
        elif wave=='square': amp=2/(math.pi*h) if h%2 else 0
        elif wave=='sawtooth': amp=2/(math.pi*h)
        else: amp=2*abs(math.sin(math.pi*h*duty))/(math.pi*h)
        if wave=='triangle' and h%2==1 and (h//2)%2: amp=-amp
        voc.append((note,f,44100,wave,h,20*math.log10(max(abs(amp),1e-12))))
    write('vco_spectrum.csv',['note_number','frequency_hz','sample_rate','waveform','harmonic_number','harmonic_amplitude_db'],voc)
    # Representative linear ADSR trajectory with stage labels.
    eg=[]; fs=44100; stages=[('attack',.01,1.),('decay',.2,.6),('sustain',.15,.6),('release',.3,0.)]; i=0; prev=0
    for name,dur,target in stages:
      count=int(fs*dur)
      for j in range(count):
       val=prev+(target-prev)*(j+1)/count; eg.append((i,i/fs,name,val)); i+=1
      prev=target
    write('eg_trajectory.csv',['sample_index','time_seconds','envelope_stage','envelope_value'],eg)
    print('Wrote baseline CSVs to',os.path.abspath(OUT))
if __name__=='__main__': run()
