name: CheapSynth01 Tests

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libjack-jackd2-dev libcurl4-openssl-dev libfreetype6-dev libx11-dev libxcomposite-dev libxcursor-dev libxinerama-dev libxrandr-dev libxrender-dev
      
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install cmake
      
      - name: Setup MSBuild
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Configure and build tests
        run: |
          mkdir -p build_tests
          cd build_tests
          cmake .. -DSTANDALONE_ONLY=ON
          cmake --build . --target CheapSynth01Tests --config Debug
      
      - name: Run tests
        id: run_tests
        run: |
          cd build_tests
          if [ "$RUNNER_OS" == "Windows" ]; then
            ./Tests/CheapSynth01Tests_artefacts/Debug/CheapSynth01Tests.exe
          else
            ./Tests/CheapSynth01Tests_artefacts/Debug/CheapSynth01Tests
          fi
        shell: bash
        continue-on-error: true
        
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results-${{ runner.os }}
          path: build_tests/test_results.xml
          
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: runner.os == 'Linux' && always()
        with:
          files: build_tests/test_results.xml
          
      - name: Check test status
        if: steps.run_tests.outcome != 'success'
        run: exit 1
